[package]
name = "mcrs-core"
version = "0.1.0"
edition = "2021"

[lib]

[[bin]]
name = "mcrs-core"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
